services:
    ablett.twig_extension.twig_faker_extension:
        class: Ablett\TwigFaker\TwigFakerExtension
        tags:
            - { name: 'twig.extension' }
    custom.twig.extension.debug:
        class: Twig_Extension_Debug
        tags:
            - { name: 'twig.extension' }
